name: linux-memory-fill-progressive
identity: linuxmemoryfillprogressive
kind: ChaosExperimentTemplate
apiVersion: litmuschaos.io/v1beta1
spec:
  infraType: Linux
  faults:
    - name: linux-memory-stress-p25
      identity: linux-memory-stress
      revision: v1
      isEnterprise: true
      values:
        - name: DURATION
          value: 60s
        - name: MEMORY
          value: 25%
        - name: WORKERS
          value: <+experiment.variables.worker_count>
      authEnabled: false
    - name: linux-memory-stress-p50
      identity: linux-memory-stress
      revision: v1
      isEnterprise: true
      values:
        - name: DURATION
          value: 60s
        - name: MEMORY
          value: 50%
        - name: WORKERS
          value: <+experiment.variables.worker_count>
      authEnabled: false
    - name: linux-memory-stress-p75
      identity: linux-memory-stress
      revision: v1
      isEnterprise: true
      values:
        - name: DURATION
          value: 60s
        - name: MEMORY
          value: 75%
        - name: WORKERS
          value: <+experiment.variables.worker_count>
      authEnabled: false
  actions:
    - isRemote: true
      name: delay-nuy
      identity: delay
      isEnterprise: false
      continueOnCompletion: false
      values: []
    - isRemote: true
      name: delay-udk
      identity: delay
      isEnterprise: false
      continueOnCompletion: false
      values: []
    - isRemote: true
      name: delay-0fh
      identity: delay
      isEnterprise: false
      continueOnCompletion: false
      values: []
  vertices:
    - name: v-start
      start:
        faults:
          - name: linux-memory-stress-p25
      end: {}
    - name: v-nvx
      start:
        actions:
          - name: delay-nuy
      end:
        faults:
          - name: linux-memory-stress-p25
    - name: v-25to50
      start:
        faults:
          - name: linux-memory-stress-p50
      end:
        actions:
          - name: delay-nuy
    - name: v-ueg
      start:
        actions:
          - name: delay-udk
      end:
        faults:
          - name: linux-memory-stress-p50
    - name: v-50to75
      start:
        faults:
          - name: linux-memory-stress-p75
      end:
        actions:
          - name: delay-udk
    - name: v-0gb
      start:
        actions:
          - name: delay-0fh
      end:
        faults:
          - name: linux-memory-stress-p75
    - name: v-end
      start: {}
      end:
        actions:
          - name: delay-0fh
  cleanupPolicy: delete
revision: v1
isDefault: true
variables:
  - name: worker_count
    type: String
    value: <+input>
