name: pod-jvm-method-exception
identity: podjvmmethodexception
kind: ChaosExperimentTemplate
apiVersion: litmuschaos.io/v1beta1
spec:
  infraType: KubernetesV2
  faults:
    - name: pod-jvm-method-exception-3cg
      identity: pod-jvm-method-exception
      revision: v1
      isEnterprise: true
      values:
        - name: TARGET_WORKLOAD_KIND
          value: deployment
        - name: TARGET_WORKLOAD_NAMESPACE
          value: <+input>
        - name: TARGET_WORKLOAD_NAMES
          value: <+input>
        - name: TOTAL_CHAOS_DURATION
          value: 180
        - name: POD_AFFECTED_PERCENTAGE
          value: 100
        - name: JAVA_HOME
          value: <+input>
        - name: METHOD
          value: <+input>
        - name: CLASS
          value: <+input>
        - name: EXCEPTION
          value: <+input>
      authEnabled: false
  vertices:
    - name: v-3df
      start:
        faults:
          - name: pod-jvm-method-exception-3cg
      end: {}
    - name: v-end
      start: {}
      end:
        faults:
          - name: pod-jvm-method-exception-3cg
  cleanupPolicy: delete
revision: v1
isDefault: true
