name: linux-cpu-stress-progressive
identity: linuxcpustressprogressive
kind: ChaosExperimentTemplate
apiVersion: litmuschaos.io/v1beta1
spec:
  infraType: Linux
  faults:
    - name: linux-cpu-stress-p50
      identity: linux-cpu-stress
      revision: "1"
      isEnterprise: true
      values:
        - name: DURATION
          value: 60s
        - name: LOAD
          value: "50"
        - name: WORKERS
          value: <+experiment.variables.worker_count>
    - name: linux-cpu-stress-p75
      identity: linux-cpu-stress
      revision: "1"
      isEnterprise: true
      values:
        - name: DURATION
          value: 60s
        - name: LOAD
          value: "75"
        - name: WORKERS
          value: <+experiment.variables.worker_count>
    - name: linux-cpu-stress-p100
      identity: linux-cpu-stress
      revision: "1"
      isEnterprise: true
      values:
        - name: DURATION
          value: 60s
        - name: LOAD
          value: "100"
        - name: WORKERS
          value: <+experiment.variables.worker_count>
  actions:
    - name: delay-vm-jd5
      identity: delay-vm
      isEnterprise: false
      continueOnCompletion: false
      values: []
    - name: delay-vm-xqq
      identity: delay-vm
      isEnterprise: false
      continueOnCompletion: false
      values: []
    - name: delay-vm-e0i
      identity: delay-vm
      isEnterprise: false
      continueOnCompletion: false
      values: []
  vertices:
    - name: v-start
      start:
        faults:
          - name: linux-cpu-stress-p50
      end: {}
    - name: v-je5
      start:
        actions:
          - name: delay-vm-jd5
      end:
        faults:
          - name: linux-cpu-stress-p50
    - name: v-50to75
      start:
        faults:
          - name: linux-cpu-stress-p75
      end:
        actions:
          - name: delay-vm-jd5
    - name: v-xrq
      start:
        actions:
          - name: delay-vm-xqq
      end:
        faults:
          - name: linux-cpu-stress-p75
    - name: v-75to100
      start:
        faults:
          - name: linux-cpu-stress-p100
      end:
        actions:
          - name: delay-vm-xqq
    - name: v-e1f
      start:
        actions:
          - name: delay-vm-e0i
      end:
        faults:
          - name: linux-cpu-stress-p100
    - name: v-end
      start: {}
      end:
        actions:
          - name: delay-vm-e0i
  cleanupPolicy: delete
variables:
  - name: worker_count
    value: <+input>
    type: String
    required: false
revision: v1
isDefault: true
