name: linux-memory-fill-progressive
identity: linuxmemoryfillprogressive
kind: ChaosExperimentTemplate
apiVersion: litmuschaos.io/v1beta1
spec:
  infraType: Linux
  faults:
    - name: linux-memory-stress-p25
      identity: linux-memory-stress
      revision: v1
      isEnterprise: true
      values:
        - name: DURATION
          value: 60s
        - name: MEMORY
          value: 25%
        - name: WORKERS
          value: <+experiment.variables.worker_count>
      authEnabled: false
    - name: linux-memory-stress-p50
      identity: linux-memory-stress
      revision: v1
      isEnterprise: true
      values:
        - name: DURATION
          value: 60s
        - name: MEMORY
          value: 50%
        - name: WORKERS
          value: <+experiment.variables.worker_count>
      authEnabled: false
    - name: linux-memory-stress-p75
      identity: linux-memory-stress
      revision: v1
      isEnterprise: true
      values:
        - name: DURATION
          value: 60s
        - name: MEMORY
          value: 75%
        - name: WORKERS
          value: <+experiment.variables.worker_count>
      authEnabled: false
  actions:
    - name: delay-vm-b62
      identity: delay-vm
      isEnterprise: false
      continueOnCompletion: false
      values: []
    - name: delay-vm-mgy
      identity: delay-vm
      isEnterprise: false
      continueOnCompletion: false
      values: []
    - name: delay-vm-3ti
      identity: delay-vm
      isEnterprise: false
      continueOnCompletion: false
      values: []
  vertices:
    - name: v-start
      start:
        faults:
          - name: linux-memory-stress-p25
      end: {}
    - name: v-b73
      start:
        actions:
          - name: delay-vm-b62
      end:
        faults:
          - name: linux-memory-stress-p25
    - name: v-25to50
      start:
        faults:
          - name: linux-memory-stress-p50
      end:
        actions:
          - name: delay-vm-b62
    - name: v-mhw
      start:
        actions:
          - name: delay-vm-mgy
      end:
        faults:
          - name: linux-memory-stress-p50
    - name: v-50to75
      start:
        faults:
          - name: linux-memory-stress-p75
      end:
        actions:
          - name: delay-vm-mgy
    - name: v-3ui
      start:
        actions:
          - name: delay-vm-3ti
      end:
        faults:
          - name: linux-memory-stress-p75
    - name: v-end
      start: {}
      end:
        actions:
          - name: delay-vm-3ti
  cleanupPolicy: delete
variables:
  - name: worker_count
    value: <+input>
    type: String
    required: false
revision: v1
isDefault: true
