name: linux-network-latency-progressive
identity: linuxnetworklatencyprogressive
kind: ChaosExperimentTemplate
apiVersion: litmuschaos.io/v1beta1
spec:
  infraType: Linux
  faults:
    - name: linux-network-latency-200ms
      identity: linux-network-latency
      revision: v1
      isEnterprise: true
      values:
        - name: DURATION
          value: 120s
        - name: NETWORK_LATENCY
          value: 200
      authEnabled: false
    - name: linux-network-latency-500ms
      identity: linux-network-latency
      revision: v1
      isEnterprise: true
      values:
        - name: DURATION
          value: 120s
        - name: NETWORK_LATENCY
          value: 500
      authEnabled: false
    - name: linux-network-latency-1000ms
      identity: linux-network-latency
      revision: v1
      isEnterprise: true
      values:
        - name: DURATION
          value: 120s
        - name: NETWORK_LATENCY
          value: 1000
      authEnabled: false
    - name: linux-network-latency-2000ms
      identity: linux-network-latency
      revision: v1
      isEnterprise: true
      values:
        - name: DURATION
          value: 120s
        - name: NETWORK_LATENCY
          value: 2000
      authEnabled: false
  actions:
    - name: delay-vm-quf
      identity: delay-vm
      isEnterprise: false
      continueOnCompletion: false
      values: []
    - name: delay-vm-bab
      identity: delay-vm
      isEnterprise: false
      continueOnCompletion: false
      values: []
    - name: delay-vm-p8n
      identity: delay-vm
      isEnterprise: false
      continueOnCompletion: false
      values: []
    - name: delay-vm-yqr
      identity: delay-vm
      isEnterprise: false
      continueOnCompletion: false
      values: []
  vertices:
    - name: v-start
      start:
        faults:
          - name: linux-network-latency-200ms
      end: {}
    - name: v-qvh
      start:
        actions:
          - name: delay-vm-quf
      end:
        faults:
          - name: linux-network-latency-200ms
    - name: v-200to500
      start:
        faults:
          - name: linux-network-latency-500ms
      end:
        actions:
          - name: delay-vm-quf
    - name: v-bbc
      start:
        actions:
          - name: delay-vm-bab
      end:
        faults:
          - name: linux-network-latency-500ms
    - name: v-500to1000
      start:
        faults:
          - name: linux-network-latency-1000ms
      end:
        actions:
          - name: delay-vm-bab
    - name: v-p9p
      start:
        actions:
          - name: delay-vm-p8n
      end:
        faults:
          - name: linux-network-latency-1000ms
    - name: v-1000to2000
      start:
        faults:
          - name: linux-network-latency-2000ms
      end:
        actions:
          - name: delay-vm-p8n
    - name: v-yrp
      start:
        actions:
          - name: delay-vm-yqr
      end:
        faults:
          - name: linux-network-latency-2000ms
    - name: v-end
      start: {}
      end:
        actions:
          - name: delay-vm-yqr
  cleanupPolicy: delete
revision: v1
isDefault: true
